// Phone-number backfill helper.
//
//   node scripts/phones.js list            → TSV of bars still missing a phone
//   node scripts/phones.js list --all      → every bar, phone or not
//   node scripts/phones.js merge f.json    → merge {"slug":"612-555-1234"} into bars.json
//
// The merge step normalizes to E.164 and REFUSES anything that isn't a valid
// US number, so a bad lookup can't quietly land in the dataset. Same standard
// as the rest of the pipeline: a number counts only when it was read off the
// bar's own site (docs/ingest.md step 3).
import { readFileSync, writeFileSync } from 'node:fs';
import { normalizePhone } from '../src/lib/adminform.js';

const path = new URL('../seed/bars.json', import.meta.url);
const load = () => JSON.parse(readFileSync(path, 'utf8'));

function list(all) {
  const { bars } = load();
  const rows = bars.filter(b => all || !b.phone);
  for (const b of rows) {
    console.log([b.slug, b.name, b.website || '', b.address || ''].join('\t'));
  }
  console.error(`${rows.length} bar(s)${all ? '' : ' missing a phone'}`);
}

function merge(file) {
  const found = JSON.parse(readFileSync(file, 'utf8'));
  const data = load();
  const bySlug = new Map(data.bars.map(b => [b.slug, b]));
  let ok = 0, bad = 0, unknown = 0, unchanged = 0;

  for (const [slug, raw] of Object.entries(found)) {
    const bar = bySlug.get(slug);
    if (!bar) { console.error(`! unknown slug: ${slug}`); unknown++; continue; }
    if (raw == null || raw === '' || String(raw).toUpperCase() === 'NONE') continue;
    const e164 = normalizePhone(raw);
    if (!e164) { console.error(`! not a US number, skipped: ${slug} = ${raw}`); bad++; continue; }
    if (bar.phone === e164) { unchanged++; continue; }
    bar.phone = e164;
    ok++;
  }

  // Keep bars.json key order stable: phone sits right after website.
  data.bars = data.bars.map(b => {
    if (!b.phone) return b;
    const { phone, ...rest } = b;
    const out = {};
    for (const k of Object.keys(rest)) {
      out[k] = rest[k];
      if (k === 'website') out.phone = phone;
    }
    if (!('phone' in out)) out.phone = phone;
    return out;
  });

  writeFileSync(path, JSON.stringify(data, null, 2) + '\n');
  console.error(`merged ${ok} new, ${unchanged} already set, ${bad} rejected, ${unknown} unknown slug(s)`);
}

/**
 * Emit UPDATE statements touching ONLY phone and instagram.
 *
 * Deliberately not seed.js: that upserts every column for every bar, so
 * running it against prod would overwrite any admin edit made since the last
 * scripts/export.js snapshot. These two columns are new and NULL everywhere,
 * so a targeted UPDATE cannot clobber anything.
 */
function sql() {
  const { bars } = load();
  const q = s => `'${String(s).replace(/'/g, "''")}'`;
  let n = 0;
  console.log('-- generated by scripts/phones.js sql — phone + instagram only');
  for (const b of bars) {
    const sets = [];
    if (b.phone) sets.push(`phone = ${q(b.phone)}`);
    if (b.instagram) sets.push(`instagram = ${q(b.instagram)}`);
    if (!sets.length) continue;
    console.log(`UPDATE bars SET ${sets.join(', ')} WHERE slug = ${q(b.slug)};`);
    n++;
  }
  console.error(`${n} UPDATE statement(s)`);
}

const [cmd, arg] = process.argv.slice(2);
if (cmd === 'list') list(arg === '--all');
else if (cmd === 'merge' && arg) merge(arg);
else if (cmd === 'sql') sql();
else {
  console.error('usage: phones.js list [--all] | merge <results.json> | sql');
  process.exit(1);
}
