// Emit seed/seed.sql from seed/bars.json for `wrangler d1 execute --file`.
import { readFileSync, writeFileSync } from 'node:fs';

const q = s => `'${String(s ?? '').replace(/'/g, "''")}'`;
const { bars } = JSON.parse(readFileSync(new URL('../seed/bars.json', import.meta.url)));

let sql = '-- generated by scripts/seed.js — edit seed/bars.json instead\n';
sql += 'DELETE FROM happy_hours;\nDELETE FROM bars;\n';
bars.forEach((b, i) => {
  const id = i + 1;
  sql += `INSERT INTO bars (id, slug, name, city, neighborhood, lat, lng, website, patio, rooftop, skyway, verified, last_verified, notes, price, category, seating, food) VALUES (` +
    `${id}, ${q(b.slug)}, ${q(b.name)}, ${q(b.city)}, ${q(b.neighborhood)}, ${b.lat}, ${b.lng}, ${q(b.website)}, ` +
    `${b.patio ? 1 : 0}, ${b.rooftop ? 1 : 0}, ${b.skyway ? 1 : 0}, ${b.verified ? 1 : 0}, ` +
    `${b.last_verified ? q(b.last_verified) : 'NULL'}, ${q(b.notes)}, ` +
    `${b.price ? b.price : 'NULL'}, ${q(b.category)}, ${q(b.seating)}, ${q(b.food)});\n`;
  for (const hh of b.hh) {
    sql += `INSERT INTO happy_hours (bar_id, dow_mask, start_min, end_min, deals) VALUES (` +
      `${id}, ${hh.dow_mask}, ${hh.start_min}, ${hh.end_min}, ${q(hh.deals)});\n`;
  }
});
writeFileSync(new URL('../seed/seed.sql', import.meta.url), sql);
console.log(`wrote seed/seed.sql — ${bars.length} bars, ${bars.reduce((n, b) => n + b.hh.length, 0)} windows`);
