// Emit seed/seed.sql from seed/bars.json for `wrangler d1 execute --file`.
//
// D1 is the source of truth (docs/plans/2026-07-16-admin-ui-plan.md): the SQL
// is slug-keyed UPSERTs — never `DELETE FROM bars`, never explicit ids — so
// admin edits and stable bar ids survive a reseed, and happy_hours rows are
// replaced per bar via the bar's current id. Removing a bar is an explicit
// step (skiplist + manual DELETE), not an implicit omission from bars.json.
//
// Before an ingest merge, refresh bars.json from D1 first (scripts/export.js)
// or a stale file will overwrite newer admin edits.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const q = s => `'${String(s ?? '').replace(/'/g, "''")}'`;

const BAR_COLS = [
  'slug', 'name', 'city', 'neighborhood', 'lat', 'lng', 'website', 'patio',
  'rooftop', 'skyway', 'verified', 'last_verified', 'notes', 'price',
  'category', 'seating', 'food', 'hours', 'address', 'state', 'zip',
  'phone', 'instagram', 'closed', 'closed_note',
];

function barValues(b) {
  return [
    q(b.slug), q(b.name), q(b.city), q(b.neighborhood), b.lat, b.lng, q(b.website),
    b.patio ? 1 : 0, b.rooftop ? 1 : 0, b.skyway ? 1 : 0, b.verified ? 1 : 0,
    b.last_verified ? q(b.last_verified) : 'NULL', q(b.notes),
    b.price ? b.price : 'NULL', q(b.category), q(b.seating), q(b.food),
    b.hours && b.hours.length ? q(JSON.stringify(b.hours)) : 'NULL',
    b.address ? q(b.address) : 'NULL', q(b.state || 'MN'), b.zip ? q(b.zip) : 'NULL',
    b.phone ? q(b.phone) : 'NULL', b.instagram ? q(b.instagram) : 'NULL',
    b.closed ? 1 : 0, b.closed_note ? q(b.closed_note) : 'NULL',
  ];
}

export function emitSql(bars) {
  let sql = '-- generated by scripts/seed.js — edit seed/bars.json instead\n';
  const updates = BAR_COLS.filter(c => c !== 'slug')
    .map(c => `${c}=excluded.${c}`).join(', ');
  for (const b of bars) {
    sql += `INSERT INTO bars (${BAR_COLS.join(', ')}) VALUES (${barValues(b).join(', ')})\n` +
      `  ON CONFLICT(slug) DO UPDATE SET ${updates};\n`;
    sql += `DELETE FROM happy_hours WHERE bar_id = (SELECT id FROM bars WHERE slug = ${q(b.slug)});\n`;
    for (const hh of b.hh) {
      sql += `INSERT INTO happy_hours (bar_id, dow_mask, start_min, end_min, deals) ` +
        `SELECT id, ${hh.dow_mask}, ${hh.start_min}, ${hh.end_min}, ${q(hh.deals)} ` +
        `FROM bars WHERE slug = ${q(b.slug)};\n`;
    }
  }
  return sql;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { bars } = JSON.parse(readFileSync(new URL('../seed/bars.json', import.meta.url)));
  writeFileSync(new URL('../seed/seed.sql', import.meta.url), emitSql(bars));
  console.log(`wrote seed/seed.sql — ${bars.length} bars, ${bars.reduce((n, b) => n + b.hh.length, 0)} windows (slug-keyed upserts)`);
}
